### ISSUE TITLE
不支持中文显示

### ISSUE THREAD

**Issue by xtvj** [KgdFnYpeu/YuvWater#2]
在csdn评论里看到“右上角，有生成yuv水印，然后用paint画字，然后看log，把yuv复制到C文件”
然后我试了下，把年月日加上，还是显示不了。会被空格代替。

**Comment by Zihao-Wu** [comment]
最新的提交里已经是年月日的显示了，你参考下

**Comment by xtvj** [comment]
> 最新的提交里已经是年月日的显示了，你参考下

万分感谢更新，以为要等好多天才会有回应，感谢感谢。

另外想请教下，要显示的文字必须要提前生成yuv，再放到C文件里么，可不可以有个初始化操作，比如视频加载前知道要显示哪几个文字，在视频加载前生成这几个文字的yuv文件放到内存。

我不太懂C语言，不知道jni里面是怎么个判断法，貌似是生成的yuv和jni里面的相匹配才能显示？
我现在想做一个自定义加载水印的功能，文字显示有难关，请教啊。

**Comment by Zihao-Wu** [comment]
你说的这种是可以的，1、把所有文字水印数组初始化放在android层，而android 层就好处理了，
bitmap 转yuv数组后保存进文件，再读取出来，然后传给c层。这样可以更换水印了。
demo里之所以这样写，是因为我当时的需求就只需要加载这些文字，还有你最好看懂那篇文章，了解yuv 格式，不懂再看其它文章，还有一些常用c语法之类 的，而且这个demo 只是一种思路，不可能包含所有业务情况，是为了让大家自己扩展的
