### ISSUE TITLE
能告之下如果要添加声音的话，需要修改哪些地方？

### ISSUE THREAD

**Issue by hzhou81** [KgdFnYpeu/YuvWater#7]
同上！

**Comment by Zihao-Wu** [comment]
推荐你看下这个 项目 https://github.com/yrom/ScreenRecorder，这是个录制屏幕+声音的，你可以参考这个项目源码，或者关键字 “MediaCodec录制视频” 查一下，大致就是把音频与视频流的数据合成一个流。希望对你有帮助

**Comment by hzhou81** [comment]
> 推荐你看下这个 项目 [https://github.com/yrom/ScreenRecorder，这是个录制屏幕+声音的，你可以参考这个项目源码，或者关键字](https://github.com/yrom/ScreenRecorder%EF%BC%8C%E8%BF%99%E6%98%AF%E4%B8%AA%E5%BD%95%E5%88%B6%E5%B1%8F%E5%B9%95+%E5%A3%B0%E9%9F%B3%E7%9A%84%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E6%BA%90%E7%A0%81%EF%BC%8C%E6%88%96%E8%80%85%E5%85%B3%E9%94%AE%E5%AD%97) “MediaCodec录制视频” 查一下，大致就是把音频与视频流的数据合成一个流。希望对你有帮助

谢谢大师

**Comment by hzhou81** [comment]
已解决
